id:vanilla-lite
date:2024-04-06
experiment_dir:/opt/auto-code-rover/experiment/
swe_bench_dir:/opt/SWE-bench/
setup_result_dir:/opt/SWE-bench/setup_result/
eval_log_dir:/opt/SWE-bench/eval_logs/

model:gemini-1.5-flash-002
temperature:0.2
conv_round_limit:2
selected_tasks_file:ast_conf/debug.txt
enable_sbfl:false
enable_layered:true
enable_validation:false
print:false
num_processes:1
notes:"Vanilla configuration."
